#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

[[ -t 0 ]] || { echo "Run this in a terminal: it needs your keyboard for each step." >&2; exit 1; }
cd "$(dirname "$0")/.."
REPO=kirhgoff/give-me-sub
TAP=kirhgoff/homebrew-tap
TOTAL_STAGES=8

banner "GiveMeSub release setup: Developer ID, notarization, Homebrew tap"

stage "Preflight"
say "Checks that gh and Xcode are signed in to the right accounts."
if gh auth status >/dev/null 2>&1; then
  note "gh is logged in as $(gh api user --jq .login)."
else
  warn "gh is not logged in; run: gh auth login"
  pause "Press Enter once gh is logged in"
fi
gh repo view "$REPO" --json name >/dev/null || { warn "can't see $REPO with gh"; exit 1; }
step "Open Xcode > Settings > Accounts and make sure your paid Apple ID is listed with your team."
pause "Press Enter once Xcode shows your Apple ID"

stage "Apple Team ID"
open_url "https://developer.apple.com/account#MembershipDetailsCard"
step "Scroll to 'Membership details' and copy the 10-character Team ID."
ask APPLE_TEAM_ID "Paste the Team ID:"
[[ "$APPLE_TEAM_ID" =~ ^[A-Z0-9]{10}$ ]] || { warn "that doesn't look like a 10-character Team ID"; exit 1; }
write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"
set_var APPLE_TEAM_ID "$APPLE_TEAM_ID"

stage "Developer ID Application certificate"
existing=$(security find-identity -v -p codesigning | grep "Developer ID Application" | grep "$APPLE_TEAM_ID" || true)
if [[ -n "$existing" ]]; then
  note "Already in your keychain:"
  note "$existing"
else
  say "Creates the certificate that signs apps distributed outside the App Store."
  step "Xcode > Settings > Accounts > select your team > Manage Certificates…"
  step "Click + (bottom left) > Developer ID Application. Only the Account Holder can do this."
  pause "Press Enter once it appears in the list"
  security find-identity -v -p codesigning | grep "Developer ID Application" || warn "still not in the keychain; check Keychain Access > My Certificates"
fi

stage "Export the certificate for CI"
say "CI needs the certificate and its private key as a password-protected .p12."
step "Open Keychain Access > login > My Certificates."
step "Right-click 'Developer ID Application: … ($APPLE_TEAM_ID)' > Export… > save as ~/Desktop/developer-id.p12"
step "Choose a strong export password when asked."
open -a "Keychain Access" || true
ask P12_PATH "Path to the exported .p12 [~/Desktop/developer-id.p12]:"
P12_PATH="${P12_PATH:-$HOME/Desktop/developer-id.p12}"
P12_PATH="${P12_PATH/#\~/$HOME}"
[[ -f "$P12_PATH" ]] || { warn "no file at $P12_PATH"; exit 1; }
ask_secret P12_PASSWORD "Export password you just chose:"
openssl pkcs12 -in "$P12_PATH" -passin "pass:$P12_PASSWORD" -nokeys -legacy >/dev/null 2>&1 \
  || openssl pkcs12 -in "$P12_PATH" -passin "pass:$P12_PASSWORD" -nokeys >/dev/null 2>&1 \
  || warn "openssl couldn't open the .p12 with that password; double-check it"
set_secret MACOS_CERTIFICATE_P12 "$(base64 -i "$P12_PATH")"
set_secret MACOS_CERTIFICATE_PASSWORD "$P12_PASSWORD"
if confirm "Delete $P12_PATH now that it's uploaded? (the certificate stays in your keychain)"; then
  rm -P "$P12_PATH" && note "deleted"
fi

stage "Notarization API key"
say "notarytool uses an App Store Connect API key, in CI and locally."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "Team Keys tab > Generate API Key (or +). Name: GiveMeSub notary. Access: Developer."
step "Copy the Issuer ID shown above the table, and the new key's Key ID."
step "Download the .p8 file. Apple only lets you download it once."
ask NOTARY_ISSUER_ID "Issuer ID:"
ask NOTARY_KEY_ID "Key ID:"
[[ -n "$NOTARY_ISSUER_ID" && -n "$NOTARY_KEY_ID" ]] || { warn "both IDs are required"; exit 1; }
ask P8_PATH "Path to the .p8 [~/Downloads/AuthKey_${NOTARY_KEY_ID}.p8]:"
P8_PATH="${P8_PATH:-$HOME/Downloads/AuthKey_${NOTARY_KEY_ID}.p8}"
P8_PATH="${P8_PATH/#\~/$HOME}"
[[ -f "$P8_PATH" ]] || { warn "no file at $P8_PATH"; exit 1; }
write_env NOTARY_ISSUER_ID "$NOTARY_ISSUER_ID"
write_env NOTARY_KEY_ID "$NOTARY_KEY_ID"
set_secret NOTARY_ISSUER_ID "$NOTARY_ISSUER_ID"
set_secret NOTARY_KEY_ID "$NOTARY_KEY_ID"
set_secret NOTARY_KEY_P8 "$(base64 -i "$P8_PATH")"
say "Saving a local notarytool profile 'givemesub-notary' (this also validates the key)…"
if xcrun notarytool store-credentials givemesub-notary --key "$P8_PATH" --key-id "$NOTARY_KEY_ID" --issuer "$NOTARY_ISSUER_ID"; then
  note "local profile saved; notarize with: xcrun notarytool submit … --keychain-profile givemesub-notary"
else
  warn "notarytool rejected the key; check the Key ID, Issuer ID and that the key has Developer access"
fi
note "Keep the .p8 somewhere safe (e.g. your password manager), then delete it from Downloads."

stage "Homebrew tap repository"
if gh repo view "$TAP" --json name >/dev/null 2>&1; then
  note "$TAP already exists."
elif confirm "Create public repo $TAP on GitHub?"; then
  gh repo create "$TAP" --public --add-readme --description "Homebrew tap for GiveMeSub" >/dev/null
  note "created https://github.com/$TAP"
else
  SKIPPED+=("create $TAP (gh repo create $TAP --public --add-readme)")
fi

stage "TAP_TOKEN for updating the cask"
say "A fine-grained token that can only write to $TAP, used by the release workflow."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: give-me-sub release. Resource owner: kirhgoff. Expiration: 1 year."
step "Repository access: Only select repositories > homebrew-tap."
step "Permissions > Repository > Contents: Read and write. Nothing else."
step "Generate token and copy it (starts github_pat_)."
ask_secret TAP_TOKEN "Paste the token:"
[[ "$TAP_TOKEN" == github_pat_* ]] || { warn "that doesn't look like a fine-grained token"; exit 1; }
set_secret TAP_TOKEN "$TAP_TOKEN"

stage "Verify"
say "Secrets on $REPO:"
gh secret list --repo "$REPO" | sed 's/^/    /'
say "Variables on $REPO:"
gh variable list --repo "$REPO" | sed 's/^/    /'
say "Signing identity:"
security find-identity -v -p codesigning | grep "Developer ID Application" | sed 's/^/    /' || warn "no Developer ID Application identity found"
pause "Press Enter to finish"

finish
